### ISSUE TITLE
Ability to register new UTIs

### ISSUE THREAD

**Issue by rgbkrk** [arlac77/uti#29]
Would this package be likely to adopt the ability to register openers for UTIs or URIs?

**Comment by arlac77** [comment]
What exactly should an opener be ?

**Comment by rgbkrk** [comment]
Application associated with the UTI.

**Comment by arlac77** [comment]
Path to the executable ?

**Comment by rgbkrk** [comment]
Yeah. Sorry it's been so long since I opened this issue that I lost track of how I even ended up at this repository.

**Comment by arlac77** [comment]
use UTIController.register(types)
